---
- name: "Creating consul user group"
  ansible.builtin.group:
    name: "{{ consul_agent_group }}"
    state: present
  become: true

- name: "Creating consul user"
  ansible.builtin.user:
    createhome: false
    group: "{{ consul_agent_group }}"
    name: "{{ consul_agent_user }}"
    shell: /bin/false
    system: true
  become: true
