---
- name: "DEBIAN | Installing requirements"
  ansible.builtin.apt:
    name:
      - dnsutils
      - jq
      - tree
      - unzip
      - uuid-runtime
    state: present
  become: true
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success
