---
- name: reload systemd
  ansible.builtin.systemd:
    name: consul
    daemon_reload: true
  become: true

- name: restart consul-agent
  ansible.builtin.service:
    name: consul
    state: restarted
  become: true
