---
- name: Reload systemd
  ansible.builtin.systemd:
    name: consul
    daemon_reload: true
  become: true

- name: Restart consul-agent
  ansible.builtin.service:
    name: consul
    state: restarted
  become: true
  when:
    - consul_agent_manage_config | bool
    - consul_agent_bin_install | bool
